### ISSUE TITLE
Ability to assign final estimate that had no votes

### ISSUE THREAD

**Issue by XjeaxaxX** [codescape/jira-scrum-poker#108]
For a JIRA issue, assume that 2 people voted for an estimate of 1.  And 2 people voted for an estimate of 10.  This is a wild example... but it shows that sometimes, the final estimate should be somewhere between what people voted for.  In this case, the final estimate should maybe be a 5.  But nobody actually voted "5", so I cannot choose it as a final estimate.

Also... would be nice in the reveal if you show what the average of all votes ended up being.  Even if it is not an integer.  For instance, an average of 1.8 might tell me the final estimate should be a 2.

**Comment by codescape** [comment]
I am not sure whether I understand you correctly. Scrum Poker for Jira already returns a bandwith between the lowest and highest vote and allows all values in between to be assigned.

For example see the following picture where admin provided the 3 and user the 8. You can then choose between 3, 5 and 8 as the agreed value:

![image](https://user-images.githubusercontent.com/398901/80733419-f9342000-8b0d-11ea-92e7-c7dc9a75bf23.png)

Do I miss something?

I am not planning to calculate the average of all values since this will cause significant complexity for allowing non numeric values in the near future. See #102 for that.

**Comment by XjeaxaxX** [comment]
I was mistaken.  I'm so sorry... I don't know how I got that wrong.  You can close this issue, as it is not an issue.  Sorry!  Thanks!
