### ISSUE TITLE
"Start Scrum Poker" button in issue details when poker session already active.

### ISSUE THREAD

**Issue by XjeaxaxX** [codescape/jira-scrum-poker#109]
When an issue already has an active poker session (or a completed one), the "Start Scrum Poker" button still shows in the issue details screen.  Is it possible to change the text of this button, such that you know it already has an active (or completed) session?

![2020-04-29_09h22_11](https://user-images.githubusercontent.com/1485215/80601410-c994f300-89fb-11ea-8d8b-261a445b7d98.png)

**Comment by codescape** [comment]
Thank you very much for this idea! My idea for a solution would look like this:

* when no session is started or session is completed show `Start Scrum Poker`
* when a session is running show `Join Scrum Poker`

I would not want to distinguish between no started session and an existing completed session because both states allow to start a new session.

This feature should be the same for the issue detail view and the issue context menu.

**Comment by XjeaxaxX** [comment]
Awesome!
